package mbud.hibernate.mapping;

/// default package
// Generated 2016-11-16 16:55:22 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cmentarz generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cmentarz", catalog = "pogrzebowka")
public class Cmentarz implements java.io.Serializable {

	private Integer id;
	private String nazwa;
	private String adres;
	private Set<Pogrzeb> pogrzeby = new HashSet<Pogrzeb>(0);

	public Cmentarz() {
	}

	public Cmentarz(String nazwa, String adres, Set<Pogrzeb> pogrzebs) {
		this.nazwa = nazwa;
		this.adres = adres;
		this.pogrzeby = pogrzebs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nazwa", length = 64)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "adres", length = 128)
	public String getAdres() {
		return this.adres;
	}

	public void setAdres(String adres) {
		this.adres = adres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cmentarz")
	public Set<Pogrzeb> getPogrzeby() {
		return this.pogrzeby;
	}

	public void setPogrzeby(Set<Pogrzeb> pogrzebs) {
		this.pogrzeby = pogrzebs;
	}

}
