package mbud.hibernate.mapping;

/// default package
// Generated 2016-11-16 16:55:22 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DomPogrzebowy generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dom_pogrzebowy", catalog = "pogrzebowka")
public class DomPogrzebowy implements java.io.Serializable {

	private Integer id;
	private String adres;
	private String telefon;
	private Set<Zamowienie> zamowienia = new HashSet<Zamowienie>(0);
	private Set<Pracownik> pracownicy = new HashSet<Pracownik>(0);
	private Set<Pogrzeb> pogrzeby = new HashSet<Pogrzeb>(0);

	public DomPogrzebowy() {
	}

	public DomPogrzebowy(String adres, String telefon) {
		this.adres = adres;
		this.telefon = telefon;
	}

	public DomPogrzebowy(String adres, String telefon, Set<Zamowienie> zamowienies, Set<Pracownik> pracowniks,
			Set<Pogrzeb> pogrzebs) {
		this.adres = adres;
		this.telefon = telefon;
		this.zamowienia = zamowienies;
		this.pracownicy = pracowniks;
		this.pogrzeby = pogrzebs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "adres", nullable = false, length = 128)
	public String getAdres() {
		return this.adres;
	}

	public void setAdres(String adres) {
		this.adres = adres;
	}

	@Column(name = "telefon", nullable = false, length = 15)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domPogrzebowy")
	public Set<Zamowienie> getZamowienia() {
		return this.zamowienia;
	}

	public void setZamowienia(Set<Zamowienie> zamowienies) {
		this.zamowienia = zamowienies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domPogrzebowy")
	public Set<Pracownik> getPracownicy() {
		return this.pracownicy;
	}

	public void setPracownicy(Set<Pracownik> pracowniks) {
		this.pracownicy = pracowniks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domPogrzebowy")
	public Set<Pogrzeb> getPogrzeby() {
		return this.pogrzeby;
	}

	public void setPogrzeby(Set<Pogrzeb> pogrzebs) {
		this.pogrzeby = pogrzebs;
	}

}
