package mbud.hibernate.mapping;

/// default package
// Generated 2016-11-16 16:55:22 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import mbud.util.StringUtil;

/**
 * Produkt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "produkt", catalog = "pogrzebowka")
public class Produkt implements java.io.Serializable {

	private Integer id;
	private String nazwa;
	private String opis;
	private double cena;
	private String sciezkaObrazka;
	private Wieniec wieniec;
	private Trumna trumna;
	private Znicz znicz;
	private Set<ZamowienieProdukt> zamowienia = new HashSet<ZamowienieProdukt>(0);

	public Produkt() {
	}

	public Produkt(String nazwa, double cena) {
		this.nazwa = nazwa;
		this.cena = cena;
	}

	public Produkt(String nazwa, String opis, double cena, String sciezkaObrazka, Wieniec wieniec, Trumna trumna,
			Znicz znicz, Set<ZamowienieProdukt> zamowienieProdukts) {
		this.nazwa = nazwa;
		this.opis = opis;
		this.cena = cena;
		this.sciezkaObrazka = sciezkaObrazka;
		this.wieniec = wieniec;
		this.trumna = trumna;
		this.znicz = znicz;
		this.zamowienia = zamowienieProdukts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nazwa", nullable = false, length = 64)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "opis", length = 65535)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@Column(name = "cena", nullable = false, precision = 8)
	public double getCena() {
		return this.cena;
	}

	public void setCena(double cena) {
		this.cena = cena;
	}

	@Column(name = "sciezka_obrazka", length = 256)
	public String getSciezkaObrazka() {
		return this.sciezkaObrazka;
	}

	public void setSciezkaObrazka(String sciezkaObrazka) {
		this.sciezkaObrazka = sciezkaObrazka;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "produkt")
	public Wieniec getWieniec() {
		return this.wieniec;
	}

	public void setWieniec(Wieniec wieniec) {
		this.wieniec = wieniec;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "produkt")
	public Trumna getTrumna() {
		return this.trumna;
	}

	public void setTrumna(Trumna trumna) {
		this.trumna = trumna;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "produkt")
	public Znicz getZnicz() {
		return this.znicz;
	}

	public void setZnicz(Znicz znicz) {
		this.znicz = znicz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.produkt")
	public Set<ZamowienieProdukt> getZamowienia() {
		return this.zamowienia;
	}

	public void setZamowienia(Set<ZamowienieProdukt> zamowienieProdukts) {
		this.zamowienia = zamowienieProdukts;
	}
	
	@Transient
	public String getCenaString() {
		return StringUtil.formatPrice(getCena());
	}
	
	@Transient
	public String getCenaLaczna(int count) {
		return StringUtil.formatPrice(getCena() * count);
	}

}
