package mbud.hibernate.mapping;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Trumna generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "trumna", catalog = "pogrzebowka")
public class Trumna implements java.io.Serializable {

	private int id;
	private Produkt produkt;
	private String material;
	private List<Pogrzeb> pogrzeby = new LinkedList<Pogrzeb>();

	public Trumna() {
	}

	public Trumna(Produkt produkt, String material) {
		this.produkt = produkt;
		this.material = material;
	}

	public Trumna(Produkt produkt, String material, List<Pogrzeb> pogrzebs) {
		this.produkt = produkt;
		this.material = material;
		this.pogrzeby = pogrzebs;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "produkt"))
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public Produkt getProdukt() {
		return this.produkt;
	}

	public void setProdukt(Produkt produkt) {
		this.produkt = produkt;
	}

	@Column(name = "material", nullable = false, length = 32)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trumna")
	public List<Pogrzeb> getPogrzeby() {
		return this.pogrzeby;
	}

	public void setPogrzeby(List<Pogrzeb> pogrzebs) {
		this.pogrzeby = pogrzebs;
	}

}
