package mbud.hibernate.mapping;

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * ZamowienieProduktId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ZamowienieProduktId implements java.io.Serializable {

	private Produkt produkt;
	private Zamowienie zamowienie;

	public ZamowienieProduktId() {
	}
	
	public ZamowienieProduktId(Zamowienie zamowienie, Produkt produkt) {
		this.produkt = produkt;
		this.zamowienie = zamowienie;
	}
	
	@JoinColumn(name = "id_produktu", referencedColumnName = "id")
	@ManyToOne(fetch = FetchType.EAGER)
	public Produkt getProdukt() {
		return produkt;
	}
	
	public void setProdukt(Produkt produkt) {
		this.produkt = produkt;
	}

	@JoinColumn(name = "id_zamowienia", referencedColumnName = "id")
	@ManyToOne(fetch = FetchType.LAZY)
	public Zamowienie getZamowienie() {
		return zamowienie;
	}
	
	public void setZamowienie(Zamowienie zamowienie) {
		this.zamowienie = zamowienie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZamowienieProduktId))
			return false;
		ZamowienieProduktId castOther = (ZamowienieProduktId) other;

		return (this.getZamowienie().getId() == castOther.getZamowienie().getId())
				&& (this.getProdukt().getId() == castOther.getProdukt().getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZamowienie().getId();
		result = 37 * result + this.getProdukt().getId();
		return result;
	}

}
