package mbud.hibernate.mapping;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ZamowienieProdukt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "zamowienie_produkt", catalog = "pogrzebowka")
public class ZamowienieProdukt implements java.io.Serializable {

	private ZamowienieProduktId id;
	private Integer ilosc;

	public ZamowienieProdukt() {
	}

	public ZamowienieProdukt(ZamowienieProduktId id) {
		this.id = id;
	}

	public ZamowienieProdukt(ZamowienieProduktId id, Integer ilosc) {
		this.id = id;
		this.ilosc = ilosc;
	}

	@EmbeddedId
	public ZamowienieProduktId getId() {
		return this.id;
	}

	public void setId(ZamowienieProduktId id) {
		this.id = id;
	}

	@Column(name = "ilosc")
	public Integer getIlosc() {
		return this.ilosc;
	}

	public void setIlosc(Integer ilosc) {
		this.ilosc = ilosc;
	}

}
