package mbud.hibernate.mapping;

// default package
// Generated 2016-11-16 16:55:22 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Znicz generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "znicz", catalog = "pogrzebowka")
public class Znicz implements java.io.Serializable {

	private int id;
	private Produkt produkt;
	private Boolean wkladWymienny;

	public Znicz() {
	}

	public Znicz(Produkt produkt) {
		this.produkt = produkt;
	}

	public Znicz(Produkt produkt, Boolean wkladWymienny) {
		this.produkt = produkt;
		this.wkladWymienny = wkladWymienny;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "produkt"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Produkt getProdukt() {
		return this.produkt;
	}

	public void setProdukt(Produkt produkt) {
		this.produkt = produkt;
	}

	@Column(name = "wklad_wymienny")
	public Boolean getWkladWymienny() {
		return this.wkladWymienny;
	}

	public void setWkladWymienny(Boolean wkladWymienny) {
		this.wkladWymienny = wkladWymienny;
	}
	
	public String czyWkladWymienny() {
		return (getWkladWymienny())? "TAK" : "NIE";
	}

}
